targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/main.dart
          - test/unload.dart
        options:
          compiler: dartdevc
          dart2js_args:
            - --enable-asserts