targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - 'test/unit/**.dart.browser_test.dart'
        release_options:
          dart2js_args:
            - --no-minify
