name: 'font_face_observer'
version: 2.0.8
description: Font load events, simple, small and efficient. Dart port of https://github.com/bramstein/fontfaceobserver
author: Rob Becker <rob.becker@workiva.com>
homepage: https://github.com/Workiva/font_face_observer

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  dart2_constant: ^1.0.0

dev_dependencies:
  test: ">=0.12.0 < 2.0.0"
  build_runner: <1.0.0
  build_test: <1.0.0
  build_web_compilers: <1.0.0
