name: 'font_face_observer'
version: 2.0.8
description: Font load events, simple, small and efficient. Dart port of https://github.com/bramstein/fontfaceobserver
author: Rob Becker <rob.becker@workiva.com>
homepage: https://github.com/Workiva/font_face_observer

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  dart2_constant: ^1.0.0

dev_dependencies:
  build_runner: ">=0.6.0<1.0.0"
  build_test: ">=0.9.0<1.0.0"
  build_web_compilers: ">=0.2.0<1.0.0"
  test: ">=0.12.30 <2.0.0"
