name: font_face_observer
version: 2.0.14
description: Font load events, simple, small and efficient. Dart port of https://github.com/bramstein/fontfaceobserver
homepage: https://github.com/Workiva/font_face_observer

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  test: ^1.9.1
  workiva_analysis_options: ^1.0.1
