name: font_face_observer
version: 3.0.1
description: Font load events, simple, small and efficient. Dart port of https://github.com/bramstein/fontfaceobserver
homepage: https://github.com/Workiva/font_face_observer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^2.0.0
  build_web_compilers: ^2.5.1
  test: ^1.16.8
  workiva_analysis_options: ^1.0.1
